service: batagoda-lambda

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  webhookHandler:
    handler: bin/handler
    events:
      - http:
          path: /
          method: post
    environment:
          CALL_WORD: atagoda